name: defaullt

on:
  push:
    branches: '*'

jobs:
  test-2:
    name: test-2
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: read
    steps:
      - name: Show test var
        run: |
          echo "TEST_HOME=/home/elastio" >> $GITHUB_ENV
          echo "TEST_HOME_123=/home/elastio" >> $GITHUB_ENV
          echo "REG=/home/elastio" >> $GITHUB_ENV
          ls -lah $GITHUB_ENV
          grep -v REG $GITHUB_ENV > /tmp/env
          cat /tmp/env > $GITHUB_ENV
          cat $GITHUB_ENV
