name: defaullt

on:
  push:
    branches: '*'

jobs:
  test-2:
    name: test-2
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: read
    steps:
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TEST: ${{ secrets.TEST }}
      - name: Show test var
        run: |
          grep -v _REGION $GITHUB_ENV > $GITHUB_ENV.tmp
          cat $GITHUB_ENV.tmp > $GITHUB_ENV
      - name: Show test var
        run: source .env && echo $TEST
