name: defaullt

on:
  push: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    if: "github.ref != 'refs/heads/main' && github.ref != 'refs/heads/main-1'"

    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: echo "foobar"

