name: defaullt

on:
  push:
    branches: [staging-bors, trying-bors]

jobs:
  test-2:
    name: test-2
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: read
    steps:
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TEST: ${{ secrets.TEST }}
      - name: Show test var
        run: source .env && echo $TEST
